name: example
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fat_dev:
    path: ..

flutter:
  uses-material-design: true
dev_dependencies: 
  test: ^1.17.10
